import { NavBar, SideBar } from '@/components/ui';
import c from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full bg-white text-black">
      <body
        className={c(
          inter.className,
          'h-svh w-full pl-[220px] pt-16 antialiased'
        )}
      >
        <NavBar />
        <SideBar />
        <main className="flex h-auto w-full items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
