import { Icon, Separator, Text } from '@/components';
import c from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full bg-white text-black">
      <body className={c(inter.className, 'size-full pl-[219px] antialiased')}>
        <aside className="fixed inset-y-0 left-0 size-full max-w-[219px] border-r border-transparents-300 bg-gray-50">
          <div className="flex w-full items-center px-3 py-4">
            <div className="flex w-full items-center gap-3.5 px-2.5 py-1.5">
              <Image
                src="/company-Icon.png"
                alt="Company Icon"
                className="size-5"
                width={20}
                height={20}
              />
              <Text size="14" weight="medium" className="line-clamp-1 w-full">
                Matt Peterson
              </Text>

              <Icon
                name="chevron-down"
                className="size-2"
                width={8}
                height={8}
              />
            </div>
          </div>
          <Separator />
        </aside>
        {children}
      </body>
    </html>
  );
}
